version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    container_name: "${CONT_NAME}"
    ports:
      - "${HOST_PORT}:22"
    volumes:
      - ./share:/home/${USER_NAME}/share
    command: ${USER_NAME}:${USER_PASS}:10001
    restart: always
