services:
  sftp:
    build: ./sftp/
    container_name: "${CONT_NAME}"
    ports:
      - "${HOST_PORT}:22"
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PASS=${USER_PASS}
    volumes:
      - ./share:/opt/SFTP-SERVER
    restart: always
